server:
  port: 9002

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:9001/eureka/}

resilience4j:
  ratelimiter:
    instances:
      userServiceRateLimiter:
        limit-refresh-period: 30s
        limit-for-period: 5
        timeout-duration: 3s
