version: '3.8'

services:
  service-discovery:
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    image: service-discovery:1.0.0
    container_name: service-discovery
    ports:
      - "9001:9001"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9001/" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: api-gateway:1.0.0
    container_name: api-gateway
    ports:
      - "9000:9000"
    networks:
      - app-network
    depends_on:
      service-discovery:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:9001/eureka/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: ./user
      dockerfile: Dockerfile
    image: user-service:1.0.0
    container_name: user-service
    ports:
      - "9002:9002"
    networks:
      - app-network
    depends_on:
      service-discovery:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:9001/eureka/

  product-service:
    build:
      context: ./product
      dockerfile: Dockerfile
    image: product-service:1.0.0
    container_name: product-service
    ports:
      - "9003:9003"
    networks:
      - app-network
    depends_on:
      service-discovery:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:9001/eureka/

  order-service:
    build:
      context: ./order
      dockerfile: Dockerfile
    image: order-service:1.0.0
    container_name: order-service
    ports:
      - "9004:9004"
    networks:
      - app-network
    depends_on:
      service-discovery:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:9001/eureka/

  payment-service:
    build:
      context: ./payment
      dockerfile: Dockerfile
    image: payment-service:1.0.0
    container_name: payment-service
    ports:
      - "9005:9005"
    networks:
      - app-network
    depends_on:
      service-discovery:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:9001/eureka/

  notification-service:
    build:
      context: ./notification
      dockerfile: Dockerfile
    image: notification-service:1.0.0
    container_name: notification-service
    ports:
      - "9006:9006"
    networks:
      - app-network
    depends_on:
      service-discovery:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:9001/eureka/

networks:
  app-network:
    driver: bridge
